server:
  port: 8082

spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/cartdb
    username: chamikajay
    password: mypassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true



