server:
  port: 8081
  ssl:
    key-store-type: PKCS12
    key-store: classpath:server.p12
    key-store-password: changeit
    client-auth: need
    trust-store: classpath:server-truststore.p12
    trust-store-password: changeit

spring:


  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: chamikajay
    password: mypassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true


springdoc:

  api-docs:
    path: /api-docs

  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method