server:
  port: 8083

spring:


  datasource:
    url: jdbc:postgresql://localhost:5432/orderdb
    username: chamikajay
    password: mypassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true


    application:
      name: order-service
