server:
  port: 8080

spring:

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: jdbc:postgresql://localhost:5432/productdb
    username: chamikajay
    password: mypassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true


aws:
  region: ap-south-1
  s3:
    bucket-name: project-velocity-bucket  # TODO: Create the bucket in AWS S3


springdoc:

  api-docs:
    path: /api-docs

  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

